#!/usr/bin/with-contenv bash

cd /config

if [ ! -d "/config/hc" ]; then
    git clone https://github.com/healthchecks/healthchecks.git /config

    # set default values for variables
    SITE_ROOT=${SITE_ROOT:-https://my-monitoring-project.com}
    SITE_NAME=${SITE_NAME:-My Monitoring Project}
    DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL:-noreply@my-monitoring-project.com}
    EMAIL_HOST=${EMAIL_HOST:-your-smtp-server-here.com}
    EMAIL_PORT=${EMAIL_PORT:-587}
    EMAIL_HOST_USER=${EMAIL_HOST_USER:-username}
    EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD:-password}
    EMAIL_USE_TLS=${EMAIL_USE_TLS:-True}

    cat <<EOF > ./hc/local_settings.py
SITE_ROOT = "$SITE_ROOT"
SITE_NAME = "$SITE_NAME"
DEFAULT_FROM_EMAIL = "$DEFAULT_FROM_EMAIL"

EMAIL_HOST = "$EMAIL_HOST"
EMAIL_PORT = "$EMAIL_PORT"
EMAIL_HOST_USER = "$EMAIL_HOST_USER"
EMAIL_HOST_PASSWORD = "$EMAIL_HOST_PASSWORD"
EMAIL_USE_TLS = $EMAIL_USE_TLS

ALLOWED_HOSTS = ["$SITE_ROOT"]
EOF

else
    git checkout master
    git pull
fi

pip install -r requirements.txt

# permissions
chown -R abc:abc \
	/config

exec \
	s6-setuidgid abc ./manage.py migrate
